sonar.projectKey=jmenz-93_front-end
sonar.organization=jmenz-93


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=front-end
#sonar.projectVersion=1.0


#Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=resume-app, mke_crime_intelligence_platform

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Coverage reports
sonar.javascript.lcov.reportPaths=resume-app/coverage/lcov.info
sonar.typescript.lcov.reportPaths=resume-app/coverage/lcov.info